travis:
  secure:
    BINSTAR_TOKEN: EfJqNEz0PFWT5pqCWvPIhPlbxCg12LpWLDksSw8ZD4LyH4zvD9o1R4GGW1h8IykBWkhxFbfnSVoZ7dUH+u37dSoBSAEmYX/Emer+k91IqttZ9+nSkRcOegAgZSuVU0nYPpN3zchqnVJm4Oa5+Yyg2W0AMGpO4uU3DC30+hfP8/p0nXbpbnYktpKu1b9prn+kfELT6cBvarPWm7nmS1uFFLHBVxDcV+bcYv7fNTovodOh6E6ME5Mj/nm4fjMiMhKsLwiZaLzRFOhLkATqW/q9hBUzV1tW9U90bVokZcF57fIx9EF9KHOUjzECMBLpaDriUwCfwNCKom6+6FLnlnM5iBkUe5gU8MMZgex3eqjYWB+llqZT+m/oYkpnc8BxpqzNpdYU3LYEecp21UbOPTBXq3G1gijsWTVF1Xsey4VMx9biuKybgs2PuBhoAZB3B4QGIbwV8fU5a9PfWmj6vqRn/cWbpipqHouJAxIMxmvbI7+dB8FgRlf9QDg706iIKDT+wrdVn82V5ns8OhddhKWHcY+bwj2WL2Wb3Zp5Iy/VTQ7Ctqu2NSki1ZPgq74TX1R8uOwHeQw+O9JZFah7/pthJrJWOxZWSCtTjcyn5DlhNqQkxCMZoQS5jAmNvG624ZoZjG7WMCZuWO5ywNj2+jwRpJEKF/PzQzI5sC3Sc0NOalU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
