travis:
  secure:
    BINSTAR_TOKEN: mqKCQxySc1l5aiDwgv/8i3DFFrIUd0Suem1+J/2mOVke3RgG0LutRt2iNRpabbdzauO0ekWa7jKayIxdPtkn384u5s7qKqvng/LgQ5C2PeMyUPLVXV9RKUWAkslos34b32oK0tkuUdsJdULc41LaU1U9ATc3LLUceq60UPnNVkLkpjw1PtsZB3L9PwWfb+ODAuM2DhOrKgGl7jxEXDgkdPy6kfP4/eb1wnltPMlvUuMUx5pdfmIGR8DNObghXemRDmKKMdHyChhZHqS9zveoirwZQOKWc8F1h5e8Qgp6OnkL3NoL0WqrI76fUehgsPwRccem6SV4Oav4ND1tpgOD3XYbYGlsicHlT9ZV8PIpmX6yLYkgiWAU4nqMrxKZ2gY4VtLrc4burzKmamShHjOT0NpL1ddjiU4w2nT1fNyLKjJQYAIe6bS6ZpR6d+MkZCUgPQmk2Avjlu/H9pHTIiRPfwStniwZlMMMYOVhgRo81PZRXKBNXmbTiK/Gx1YoFEA77s4xHF054FYL+GnbX8tkSY1+k2G6RwHXoFoyHXUnXMl+JOwMWtdt0g//VzUqzzH4Q14Ni9RNB+yCfryKmSlmJ9wkGXl7Wbr/qOPT74+FF7M74k/pSovpUnbWmUbLbK9zUQ1VJAevqF5JnG/Xw2nXjJeA8D+DmTxFSXQyvqvww2s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
